name: Node.js App Workflow

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Adjust Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Running tests
      id: generate_id
      run: |
        npm run start

    - name: Use Generated ID
      run: echo "The generated ID is $ID"

    - name: Use Generated ID2
      run: echo "The generated ID is ${{ steps.generate_id.outputs.generated_id }}"
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Extract session IDs and spec names, generate URLs
      id: generate_urls
      run: |
          urls=""
          for file in results/*.json; do
            sessionId=$(jq -r '.capabilities.sessionId' "$file")
            specName=$(jq -r '.specs[0]' "$file" | xargs basename)
            specName="${specName%%.*}"
            if [ "$sessionId" != "null" ] && [ "$specName" != "null" ]; then
              sauce_url="https://app.saucelabs.com/tests/$sessionId"
              # Shorten URL using TinyURL API
              short_url=$(curl -s "http://tinyurl.com/api-create.php?url=$sauce_url")
              echo -e "Generated Sauce Labs Run URL for spec \e[32m$specName\e[0m: \e[31m$short_url\e[0m"
              urls="$urls$specName = $short_url\n"
              urls+="\033[34mGenerated Sauce Labs Run URL for spec $specName: $short_url\033[0m\n"
            fi
          done
          echo -e "$urls" > sauce_labs_urls.txt
          echo "SAUCE_LABS_URLS=$(cat sauce_labs_urls.txt | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Display generated Sauce Labs URLs
      run: |
          echo "Sauce Labs URLs:"
          echo "${{ env.SAUCE_LABS_URLS }}"

    - name: Upload Sauce Labs URLs artifact
      uses: actions/upload-artifact@v4
      with:
          name: sauce-labs-urls
          path: sauce_labs_urls.txt
          if-no-files-found: error

    - name: Display instructions for Sauce Labs URLs
      run: |
          echo "The shortened Sauce Labs URLs have been saved to an artifact. Please download the artifact named 'sauce-labs-urls' to view the shortened links."
