name: Node.js App Workflow

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Adjust Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Running tests
      id: generate_id
      run: |
        npm run start

    - name: Use Generated ID
      run: echo "The generated ID is $ID"

    - name: Use Generated ID2
      run: echo "The generated ID is ${{ steps.generate_id.outputs.generated_id }}"
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Extract session IDs and spec names, generate URLs
      id: generate_urls
      run: |
          urls=""
          for file in results/*.json; do
            sessionId=$(jq -r '.capabilities.sessionId' "$file")
            specName=$(jq -r '.specs[0]' "$file" | xargs basename)
            specName="${specName%%.*}"
            if [ "$sessionId" != "null" ] && [ "$specName" != "null" ]; then
              sauce_url="https://app.saucelabs.com/tests/$sessionId"
              echo "Generated Sauce Labs URL for $specName: $sauce_url"
              urls="$urls$specName = $sauce_url\n"
            fi
          done
          echo -e "$urls" > sauce_labs_urls.txt
          echo "SAUCE_LABS_URLS=$(cat sauce_labs_urls.txt | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Display generated Sauce Labs URLs
      run: |
          echo "Sauce Labs URLs:"
          echo "${{ env.SAUCE_LABS_URLS }}"

    - name: Use the URLs (example step)
      run: |
          # Example of using the generated URLs
          for url in ${{ env.SAUCE_LABS_URLS }}; do
            echo "Processing URL: $url"
            # Add your URL processing logic here
          done
